# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostomOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modell', models.CharField(max_length=30)),
                ('cpu', models.CharField(help_text=b'enter a cpu of phone', max_length=200)),
                ('RAMmemory', models.IntegerField(help_text=b'enter a RAM memory in gig')),
                ('internalmemory', models.IntegerField()),
                ('qualitycamera', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'enter phone name', max_length=200)),
                ('description', models.TextField(help_text=b'enter a brif description about phone', max_length=1000)),
                ('photo', models.ImageField(blank=True, upload_to=b'product_photo')),
                ('price_in_dollars', models.DecimalField(decimal_places=2, max_digits=6)),
                ('costomoption', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.CostomOption')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneSold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_purchase', models.DateTimeField(default=django.utils.timezone.now)),
                ('phonenumber', models.PositiveIntegerField()),
                ('email', models.CharField(help_text=b'example@gmail.com', max_length=30, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[(b'a', b'Available'), (b'u', b'Unavailable'), (b'o', b'Outdated')], default=b'a', help_text=b'PHONE availability', max_length=1)),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Phone')),
            ],
        ),
    ]
