# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='price_in_dollars',
        ),
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
