# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170222_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonesold',
            name='product',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
